
const i18n = {
  it: {
    eyebrow: "Strumento di prestampa",
    title: "Booklet Imposer<br>con bleed, crocini e creep",
    lead: "Carica un PDF a pagine singole con abbondanza. Il tool crea un PDF imposto a opuscolo, aggiunge crocini di taglio in base al bleed indicato e applica lo scostamento creep calcolato dallo spessore carta o stimato dalla grammatura.",
    byline: "by <span>Gabriele Falcinelli</span>",
    instrBtn: "Come si usa",
    step1num: "01",
    step1title: "Esporta il PDF dal programma di impaginazione",
    step1text: "Esporta il file a <em>pagine singole</em> con le abbondanze (bleed) già incluse, ma <strong>senza crocini di taglio</strong>: verranno aggiunti da questo tool in fase di imposizione.",
    step2num: "02",
    step2title: "Carica il PDF e imposta i parametri",
    step2text: "Indica il valore del bleed per lato, la lunghezza e lo spessore dei crocini, e i dati della carta (grammatura o spessore manuale) per il calcolo del creep.",
    step3num: "03",
    step3title: "Analizza e genera",
    step3text: "Clicca prima su <em>Analizza PDF</em> per verificare la segnatura, poi su <em>Genera PDF imposto</em> per scaricare il file pronto per la stampa fronte/retro.",
    step4num: "04",
    step4title: "Tutto resta nel browser",
    step4text: "Nessun file viene caricato su server. L'elaborazione avviene interamente nel tuo browser, in totale privacy.",
    instrWarning: "Il bleed centrale viene tagliato in imposizione: dalla pagina sinistra viene rimossa l'abbondanza destra, dalla pagina destra viene rimossa l'abbondanza sinistra. I due trim al vivo si incontrano sulla linea di piega del dorso. <strong>Esporta sempre senza crocini applicati.</strong>",
    settingsTitle: "Impostazioni",
    dropzoneTitle: "Scegli PDF sorgente",
    dropzoneFile: "PDF a pagine singole con bleed",
    dropzoneHint: "I file restano nel browser. Nessun upload server.",
    lblBleed: "Bleed per lato (mm)",
    ttBleed: "Abbondanza per lato in mm. Indica la quantità di pagina in eccesso che verrà rifilata (spesso 3mm).",
    lblMarkLen: "Lunghezza crocini (mm)",
    ttMarkLen: "Lunghezza fisica del tratto stampato per i crocini di ritaglio (es. 5mm).",
    lblMarkOffset: "Distanza crocini dal trim (mm)",
    ttMarkOffset: "Spazio vuoto tra l'angolo di rifilo effettivo e l'inizio del crocino (es. 1.5mm o 2mm).",
    lblMarkWeight: "Spessore crocini (pt)",
    ttMarkWeight: "Spessore della linea usata per disegnare i crocini (es. 0.3pt).",
    lblGsm: "Grammatura (g/m²)",
    ttGsm: "Grammatura della carta stampata. Usata in abbinamento al Bulk per stimare lo spessore se non misurato.",
    lblBulk: "Bulk carta (cm³/g)",
    ttBulk: "Mano (o volume specifico) della carta. Carte usomano hanno solitamente bulk > 1, carte patinate < 1.",
    lblManualThick: "Spessore manuale (mm)",
    ttManualThick: "Inserisci lo spessore effettivo del singolo foglio se lo hai misurato con un micrometro. Ignora Grammatura e Bulk.",
    hintThick: "Se vuoto: spessore ≈ gram. × bulk / 1000.",
    lblCreep: "Fattore creep",
    ttCreep: "Moltiplicatore applicato al calcolo dello scostamento (creep). Aumenta o diminuisci se la piega della carta reale richiede compensazioni diverse dal teorico.",
    hintCreep: "Riduci/aumenta se la prova lo richiede.",
    lblCoverType: "Tipo Copertina",
    ttCoverType: "Auto-copertinato: la copertina è nel PDF caricato. Copertina separata: accavallata esternamente, il suo spessore si somma al creep del blocco interno.",
    optAutoCover: "Auto-copertinato (integrata nel PDF)",
    optSepCover: "Copertina separata (esterna, calcolo spessore extra)",
    extCoverTitle: "Impostazioni Copertina Esterna",
    lblCovSpreads: "Quartini copertina",
    ttCovSpreads: "Numero di fogli piegati (quartini) che formano la copertina. Solitamente 1.",
    lblCovGsm: "Grammatura (g/m²)",
    ttCovGsm: "Grammatura della carta di copertina.",
    lblCovBulk: "Bulk carta (cm³/g)",
    ttCovBulk: "Mano (o volume specifico) della carta di copertina.",
    lblCovManual: "Spess. manuale (mm)",
    ttCovManual: "Inserisci lo spessore effettivo se lo hai misurato, altrimenti usa grammatura e bulk.",
    phOptional: "opzionale",
    lblCreepMode: "Direzione compensazione creep",
    ttCreepMode: "Metodo standard: i fogli interni si stringono verso il dorso per compensare lo spessore della piega.",
    optInward: "Progressivo verso il dorso: foglio esterno fermo, fogli interni compensati",
    optNone: "Non applicare creep",
    lblColorMode: "Profilo colore dei segni applicati",
    ttColorMode: "Scegli se forzare i crocini a CMYK (Nero di registro 100/100/100/100) o RGB (Nero). Lascia in 'Auto' per rilevare dal documento.",
    optColorAuto: "Rileva automaticamente dal documento",
    optColorCmyk: "Forza CMYK (nero di registro)",
    optColorRgb: "Forza RGB (nero pieno)",
    hintColorStart: "Carica un PDF per rilevare il profilo colore.",
    lblAddMarks: "Aggiungi crocini di taglio",
    ttAddMarks: "Abilita il disegno automatico dei crocini di ritaglio su ogni pagina imposta (tranne nel lato interno del dorso).",
    lblDrawFold: "Disegna segni di piega dorso",
    ttDrawFold: "Disegna due piccoli segni di riferimento per il posizionamento esatto della piega/cordonatura al centro del foglio.",
    lblKeepOuter: "Mantieni bleed esterni e testa/piede",
    ttKeepOuter: "Mantiene il bleed su testa, piede e taglio esterno per consentire una corretta rifilatura dell'opuscolo finito.",
    btnAnalyze: "Analizza PDF",
    btnGenerate: "Genera PDF imposto",
    statusWait: "In attesa del PDF sorgente.",
    previewTitle: "Anteprima e riepilogo",
    metPages: "Pagine sorgente",
    metSheets: "Fogli imposti",
    metTrim: "Trim stimato",
    metCreep: "Creep max",
    previewNote: "Il bleed centrale viene tagliato in imposizione: dalla pagina sinistra viene rimossa l'abbondanza destra, dalla pagina destra viene rimossa l'abbondanza sinistra. In questo modo i due trim al vivo si incontrano sulla linea di piega del dorso.",
    thSheet: "Foglio",
    thSide: "Lato",
    thLeft: "Pagina sinistra",
    thRight: "Pagina destra",
    thCreep: "Creep",
    tbEmpty: "Carica un PDF per vedere la segnatura.",
    footerSig: "by <span>Gabriele Falcinelli</span> — uso libero e gratuito",
    
    // JS strings
    jsStatusLoading: "Analisi del PDF in corso…",
    jsErrNoPages: "Il PDF non contiene pagine.",
    jsErrBleedLarge: "Il bleed indicato è troppo grande rispetto alla pagina PDF.",
    jsStatusAnalyzed: "PDF analizzato. Puoi generare il booklet imposto.",
    jsErrAnalyze: "Errore analisi: ",
    jsColorDetected: "Rilevato: ",
    jsColorUndetermined: "non determinato",
    jsColorUseProfile: ". I crocini useranno questo profilo.",
    jsColorForced: ". Forzato manualmente a ",
    jsBlankPage: "Pagina bianca",
    jsBlank: "bianca",
    jsSideFront: "Fronte",
    jsSideBack: "Retro",
    jsStatusGenerating: "Generazione PDF imposto in corso…",
    jsStatusGenerated: "PDF imposto generato e scaricato. Controlla sempre una prova stampata prima della produzione.",
    jsErrGenerate: "Errore generazione: ",
    jsPreviewLeft: "Pagina sinistra",
    jsPreviewRight: "Pagina destra",
    jsPreviewNote1: "Bleed interno rimosso: i trim si toccano sulla piega",
    jsPreviewNote2: "Dorso / piega",
    jsStatusPdfLoaded: "PDF caricato. Avvio analisi…",
    jsStatusUpdated: "Impostazioni aggiornate. Rigenera il PDF per applicarle."
  },
  en: {
    eyebrow: "Prepress Tool",
    title: "Booklet Imposer<br>with bleed, crop marks and creep",
    lead: "Upload a single-page PDF with bleed. The tool creates an imposed booklet PDF, adds crop marks based on the specified bleed, and applies creep shift calculated from paper thickness or estimated from GSM.",
    byline: "by <span>Gabriele Falcinelli</span>",
    instrBtn: "How to use",
    step1num: "01",
    step1title: "Export PDF from layout software",
    step1text: "Export the file as <em>single pages</em> with bleeds already included, but <strong>without crop marks</strong>: they will be added by this tool during imposition.",
    step2num: "02",
    step2title: "Upload PDF and set parameters",
    step2text: "Set the bleed value per side, the length and thickness of crop marks, and paper data (GSM or manual thickness) to calculate the creep.",
    step3num: "03",
    step3title: "Analyze and generate",
    step3text: "First click <em>Analyze PDF</em> to verify the signature, then <em>Generate imposed PDF</em> to download the print-ready two-sided file.",
    step4num: "04",
    step4title: "Everything stays in the browser",
    step4text: "No files are uploaded to servers. Processing happens entirely in your browser, in complete privacy.",
    instrWarning: "The inner bleed is cut during imposition: right bleed is removed from the left page, and left bleed is removed from the right page. The two trims meet exactly on the spine fold line. <strong>Always export without crop marks applied.</strong>",
    settingsTitle: "Settings",
    dropzoneTitle: "Choose source PDF",
    dropzoneFile: "Single-page PDF with bleed",
    dropzoneHint: "Files stay in the browser. No server uploads.",
    lblBleed: "Bleed per side (mm)",
    ttBleed: "Bleed amount per side in mm. Indicates the excess page area that will be trimmed (often 3mm).",
    lblMarkLen: "Crop mark length (mm)",
    ttMarkLen: "Physical length of the printed line for crop marks (e.g. 5mm).",
    lblMarkOffset: "Crop mark offset (mm)",
    ttMarkOffset: "Empty space between the actual trim corner and the start of the crop mark (e.g. 1.5mm or 2mm).",
    lblMarkWeight: "Crop mark weight (pt)",
    ttMarkWeight: "Thickness of the line used to draw crop marks (e.g. 0.3pt).",
    lblGsm: "Paper weight (g/m²)",
    ttGsm: "Grammage of the printed paper. Used in combination with Bulk to estimate thickness if not measured.",
    lblBulk: "Paper bulk (cm³/g)",
    ttBulk: "Bulk (or specific volume) of the paper. Uncoated papers usually have bulk > 1, coated papers < 1.",
    lblManualThick: "Manual thickness (mm)",
    ttManualThick: "Enter the actual thickness of a single sheet if measured with a micrometer. Ignores GSM and Bulk.",
    hintThick: "If empty: thickness ≈ gsm × bulk / 1000.",
    lblCreep: "Creep factor",
    ttCreep: "Multiplier applied to the creep calculation. Increase or decrease if the actual paper fold requires different compensation.",
    hintCreep: "Reduce/increase if the printed proof requires it.",
    lblCoverType: "Cover Type",
    ttCoverType: "Self-cover: the cover is in the uploaded PDF. Separate cover: wrapped externally, its thickness is added to the inner block's creep.",
    optAutoCover: "Self-cover (integrated in PDF)",
    optSepCover: "Separate cover (external, extra thickness calculation)",
    extCoverTitle: "External Cover Settings",
    lblCovSpreads: "Cover spreads",
    ttCovSpreads: "Number of folded sheets (spreads) making up the cover. Usually 1.",
    lblCovGsm: "Cover weight (g/m²)",
    ttCovGsm: "Grammage of the cover paper.",
    lblCovBulk: "Cover bulk (cm³/g)",
    ttCovBulk: "Bulk (or specific volume) of the cover paper.",
    lblCovManual: "Manual thickness (mm)",
    ttCovManual: "Enter the actual thickness if measured, otherwise uses GSM and bulk.",
    phOptional: "optional",
    lblCreepMode: "Creep compensation direction",
    ttCreepMode: "Standard method: inner sheets are pushed towards the spine to compensate for the fold thickness.",
    optInward: "Progressive inward: outer sheet fixed, inner sheets compensated",
    optNone: "Do not apply creep",
    lblColorMode: "Crop marks color profile",
    ttColorMode: "Choose whether to force crop marks to CMYK (Registration Black 100/100/100/100) or RGB (Black). Leave on 'Auto' to detect from document.",
    optColorAuto: "Detect automatically from document",
    optColorCmyk: "Force CMYK (registration black)",
    optColorRgb: "Force RGB (solid black)",
    hintColorStart: "Upload a PDF to detect color profile.",
    lblAddMarks: "Add crop marks",
    ttAddMarks: "Enable automatic drawing of crop marks on each imposed page (except on the inner spine side).",
    lblDrawFold: "Draw fold marks",
    ttDrawFold: "Draw two small reference marks for the exact positioning of the fold/crease in the center of the sheet.",
    lblKeepOuter: "Keep outer and top/bottom bleed",
    ttKeepOuter: "Keeps the bleed on the top, bottom, and outer edge to allow proper trimming of the finished booklet.",
    btnAnalyze: "Analyze PDF",
    btnGenerate: "Generate imposed PDF",
    statusWait: "Waiting for source PDF.",
    previewTitle: "Preview and summary",
    metPages: "Source pages",
    metSheets: "Imposed sheets",
    metTrim: "Estimated trim",
    metCreep: "Max creep",
    previewNote: "The inner bleed is cut during imposition: right bleed is removed from the left page, and left bleed is removed from the right page. This way the two trims meet exactly on the spine fold line.",
    thSheet: "Sheet",
    thSide: "Side",
    thLeft: "Left page",
    thRight: "Right page",
    thCreep: "Creep",
    tbEmpty: "Upload a PDF to see the signature.",
    footerSig: "by <span>Gabriele Falcinelli</span> — free to use",
    
    // JS strings
    jsStatusLoading: "Analyzing PDF…",
    jsErrNoPages: "The PDF contains no pages.",
    jsErrBleedLarge: "The specified bleed is too large compared to the PDF page.",
    jsStatusAnalyzed: "PDF analyzed. You can generate the imposed booklet.",
    jsErrAnalyze: "Analysis error: ",
    jsColorDetected: "Detected: ",
    jsColorUndetermined: "undetermined",
    jsColorUseProfile: ". Crop marks will use this profile.",
    jsColorForced: ". Manually forced to ",
    jsBlankPage: "Blank page",
    jsBlank: "blank",
    jsSideFront: "Front",
    jsSideBack: "Back",
    jsStatusGenerating: "Generating imposed PDF…",
    jsStatusGenerated: "Imposed PDF generated and downloaded. Always check a printed proof before production.",
    jsErrGenerate: "Generation error: ",
    jsPreviewLeft: "Left page",
    jsPreviewRight: "Right page",
    jsPreviewNote1: "Inner bleed removed: trims meet on the fold",
    jsPreviewNote2: "Spine / fold",
    jsStatusPdfLoaded: "PDF loaded. Starting analysis…",
    jsStatusUpdated: "Settings updated. Regenerate the PDF to apply them."
  }
};

let currentLang = 'it';

function setLanguage(lang) {
  currentLang = lang;
  document.documentElement.lang = lang;
  
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (i18n[lang][key]) el.innerHTML = i18n[lang][key];
  });
  
  document.querySelectorAll('[data-i18n-tt]').forEach(el => {
    const key = el.getAttribute('data-i18n-tt');
    if (i18n[lang][key]) el.setAttribute('data-tooltip', i18n[lang][key]);
  });
  
  document.querySelectorAll('[data-i18n-ph]').forEach(el => {
    const key = el.getAttribute('data-i18n-ph');
    if (i18n[lang][key]) el.setAttribute('placeholder', i18n[lang][key]);
  });
  
  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.classList.toggle('active', btn.dataset.lang === lang);
  });
  
  // Dispatch event for app.js to catch
  window.dispatchEvent(new Event('languageChanged'));
}

document.addEventListener('DOMContentLoaded', () => {
  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.addEventListener('click', (e) => setLanguage(e.target.dataset.lang));
  });
});
